name = "SpikeSynchrony"
uuid = "3713708d-6816-4a57-846e-904b81e02fa1"
authors = ["George Datseris <datseris.george@gmail.com>"]
version = "0.1.1"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
